### ISSUE TITLE
Models and repositories

### ISSUE THREAD

**Issue by zivko11** [zivko11/Internet-Software-Architectures#3]
Set entities based on database tables.

**Comment by zivko11** [comment]
User model class created.

**Comment by zivko11** [comment]
Vital model classes added to project.

**Comment by zivko11** [comment]
Created base repository with repository interface. Session with database established.

**Comment by zivko11** [comment]
Implemented Unit of Work pattern.

**Comment by zivko11** [comment]
CRUD operations on database successfully tested.

**Comment by zivko11** [comment]
Created CinemaTheatre repository and successfully tested.

**Comment by nikola310** [comment]
Created fan zone and props repository.

**Comment by zivko11** [comment]
Database modified. Created new entities. New POJO classes generated.

**Comment by zivko11** [comment]
Key generating changed to increment in all entities. Read all function implemented and tested successfully.

**Comment by zivko11** [comment]
All repositories and unit tests created.

**Comment by nikola310** [comment]
Props, History and FanZone succesfully tested.

**Comment by nikola310** [comment]
Repository logic improved.

**Comment by nikola310** [comment]
Props and FanZone repositories tested (again).

**Comment by nikola310** [comment]
Added read all tests for Fan Zone and Props.

**Comment by zivko11** [comment]
All model and Jpa repositories are finished.
