### ISSUE TITLE
Registered user business logic

### ISSUE THREAD

**Issue by zivko11** [zivko11/Internet-Software-Architectures#4]
Created all DTO classes and base manager interface with user manager interface. Implemented user manager with CRUD operations.

**Comment by zivko11** [comment]
Implemented FriendsList and CinemaTheatre managers and successfully tested.

**Comment by zivko11** [comment]
All managers and DTO classes created.

**Comment by zivko11** [comment]
All managers successfully tested.

**Comment by nikola310** [comment]
HistoryManager interface and implementation added. Succesfully tested Props, FanZone and History managers.
