### ISSUE TITLE
Integration tests

### ISSUE THREAD

**Issue by zivko11** [zivko11/Internet-Software-Architectures#7]
Testing REST controllers through managers to the mocked Jpa repositories. Looking is same data forwarded to controller will be same from Jpa repository output.

**Comment by zivko11** [comment]
Created all tests for CRUD operations in REST controller for Actor entity.

**Comment by nikola310** [comment]
CRUD operations in REST controller for FanZone and Props successfully tested.

**Comment by zivko11** [comment]
All controllers successfully tested.
